mp.messaging.incoming.onput-topic.connector=smallrye-kafka
mp.messaging.incoming.onput-topic.topic=output-topic
mp.messaging.incoming.onput-topic.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.output-topic.bootstrap.servers=my-kafka-kafka-bootstrap.kafka.svc:9092